const USERS={guest:{uid:1001,gid:1001,groups:['guest'],home:'/home/guest',shell:'/bin/bash',password:'guest'},user:{uid:1000,gid:1000,groups:['users','sudo'],home:'/home/henry',shell:'/bin/bash',password:'henry'},admin:{uid:900,gid:900,groups:['admin','sudo','users'],home:'/home/admin',shell:'/bin/bash',password:'admin'},root:{uid:0,gid:0,groups:['root','sudo','admin'],home:'/root',shell:'/bin/bash',password:'root'}};
const COMMANDS=['alias','apt','apt-get','bash','bg','banner','cat','cd','chmod','chown','clear','cp','curl','date','df','dig','dpkg','du','echo','env','exit','export','fastfetch','fg','find','free','grep','groups','gunzip','head','history','hostname','htop','id','ifconfig','ip','jobs','kill','less','ls','lsblk','lscpu','lspci','lsusb','matrix','mkdir','motd','mv','nano','neofetch','netstat','network','nslookup','passwd','ping','pkill','printenv','ps','pwd','reboot','rm','rmdir','route','service','shutdown','ss','su','sudo','sysinfo','systemctl','tail','tar','timedatectl','top','touch','tracepath','traceroute','uname','unzip','uptime','users','wget','whoami','which','zip'];
const clone=o=>JSON.parse(JSON.stringify(o));const dir=(name,owner='root',group='root',children={})=>({type:'dir',name,owner,group,mode:'drwxr-xr-x',children});const file=(name,content='',owner='root',group='root',mode='-rw-r--r--')=>({type:'file',name,content,owner,group,mode});
const INITIAL=dir('/', 'root','root',{bin:dir('bin','root','root',{bash:file('bash','virtual ELF bash','root','root','-rwxr-xr-x'),sh:file('sh','virtual ELF sh','root','root','-rwxr-xr-x')}),boot:dir('boot','root','root',{'vmlinuz-6.8.0':file('vmlinuz-6.8.0','Linux virtual kernel 6.8.0')}),dev:dir('dev'),etc:dir('etc','root','root',{hostname:file('hostname','henry\n'),hosts:file('hosts','127.0.0.1 localhost\n127.0.1.1 henry\n'),'os-release':file('os-release','PRETTY_NAME="Ubuntu Simulator"\nVERSION="24.04 LTS"\n')}),home:dir('home','root','root',{henry:dir('henry','user','users',{Desktop:dir('Desktop','user','users'),Documents:dir('Documents','user','users',{'welcome.txt':file('welcome.txt','Welcome to your virtual Linux home.\n','user','users')}),Downloads:dir('Downloads','user','users'),Pictures:dir('Pictures','user','users'),Videos:dir('Videos','user','users')}),guest:dir('guest','guest','guest'),admin:dir('admin','admin','admin')}),lib:dir('lib'),media:dir('media'),mnt:dir('mnt'),opt:dir('opt'),proc:dir('proc'),root:dir('root','root','root',{'.bashrc':file('.bashrc','# root configuration\n','root','root','-rw-------')}),run:dir('run'),sbin:dir('sbin'),srv:dir('srv'),sys:dir('sys'),tmp:dir('tmp'),usr:dir('usr','root','root',{bin:dir('bin'),local:dir('local'),share:dir('share')}),var:dir('var','root','root',{log:dir('log','root','root',{syslog:file('syslog','Aug 30 17:50 henry systemd[1]: Started virtual services.\n')})})});
function loadFS(){try{return JSON.parse(localStorage.getItem('henry-linux-fs'))||clone(INITIAL)}catch{return clone(INITIAL)}}let fs=loadFS();
function saveFS(){try{localStorage.setItem('henry-linux-fs',JSON.stringify(fs))}catch{}}
function resolve(cwd,p='.') {if(p==='~')return USERS[state.user].home;const raw=p.startsWith('/')?p:`${cwd}/${p}`,a=[];for(const x of raw.split('/')){if(!x||x==='.')continue;if(x==='..')a.pop();else a.push(x)}return '/'+a.join('/')||'/'}
function node(path){if(path==='/')return fs;let n=fs;for(const x of path.split('/').filter(Boolean)){if(n.type!=='dir'||!n.children[x])return null;n=n.children[x]}return n}
function parent(path){const p=resolve('/',path),a=p.split('/').filter(Boolean),name=a.pop()||'';return{p:node('/'+a.join('/')),name}}
function tok(s){const a=[];let c='',q=null;for(let i=0;i<s.length;i++){let x=s[i];if(q){if(x===q)q=null;else c+=x;continue}if(x==='"'||x==="'"){q=x;continue}if(/\s/.test(x)){if(c){a.push(c);c=''}continue}if(x==='|'||x===';'||x==='>'||x==='&'){if(c){a.push(c);c=''}if(x==='>'&&s[i+1]==='>'){a.push('>>');i++}else if(x==='&'&&s[i+1]==='&'){a.push('&&');i++}else a.push(x);continue}c+=x}if(c)a.push(c);return a}
function expand(x){return x.replace(/\$(\w+|\{[^}]+\})/g,(_,k)=>{k=k.replace(/[{}]/g,'');return state.env[k]??(k==='USER'?state.user:k==='HOME'?USERS[state.user].home:k==='PWD'?state.cwd:'')})}
let sessions=[];let state=null;let seq=0;const terminal=document.getElementById('terminal'),tabs=document.getElementById('tabs');
function newSession(){return{id:crypto.randomUUID(),title:'henry',user:'user',cwd:'/',input:'',history:[],hi:-1,env:{LANG:'en_US.UTF-8',SHELL:'/bin/bash',TERM:'xterm-256color',PATH:'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',HOME:'/home/henry'},aliases:{},lines:[{type:'system',text:'Ubuntu Simulator 24.04 LTS · Linux 6.8.0-virtual · bash 5.2'},{type:'system',text:'Safe browser sandbox: no host commands are executed.'},{type:'system',text:'Try: neofetch · ls -la · sudo apt update · curl https://api.github.com'}],stack:[],login:[],password:null}}
function prompt(){const home=USERS[state.user].home,place=state.cwd===home?'~':state.cwd;return `${state.user}@henry:${state.user==='root'&&place==='~'?'~':place}${state.user==='root'?'#':'$'}`}
function renderTabs(){tabs.innerHTML='';sessions.forEach(s=>{const b=document.createElement('button');b.className='tab '+(s.id===state.id?'active':'');b.innerHTML='<span class="tab-dot"></span>'+s.title+(sessions.length>1?'<span class="tab-close">×</span>':'');b.onclick=()=>{state=s;render()};b.querySelector('.tab-close')?.addEventListener('click',e=>{e.stopPropagation();if(sessions.length>1){sessions=sessions.filter(x=>x.id!==s.id);state=sessions[0];render()}});tabs.appendChild(b)});const plus=document.createElement('button');plus.className='add-tab';plus.textContent='+';plus.onclick=()=>{const s=newSession();s.title='terminal-'+(sessions.length+1);s.user=state.user;s.cwd=state.cwd;s.env={...state.env};sessions.push(s);state=s;render()};tabs.appendChild(plus)}
function render(){renderTabs();terminal.innerHTML='';state.lines.forEach(l=>{const d=document.createElement('div');d.className='line '+l.type;d.textContent=l.text;terminal.appendChild(d)});const row=document.createElement('div');row.className='input-row';const p=document.createElement('span');p.className='prompt';p.textContent=prompt()+' ';const input=document.createElement('input');input.value=state.input;input.autocomplete='off';input.spellcheck=false;input.oninput=()=>state.input=input.value;input.onkeydown=key;row.append(p,input,document.createElement('span'));row.lastChild.className='cursor';terminal.appendChild(row);document.getElementById('window-title').textContent=prompt();document.getElementById('session-info').textContent=`${state.user}@henry · ${state.cwd}`;input.focus();terminal.scrollTop=terminal.scrollHeight}
function print(text,type='output'){String(text).split('\n').forEach(t=>state.lines.push({type,text:t}));render()}
function runLine(raw){if(!raw.trim())return;state.history.push(raw);state.hi=-1;state.lines.push({type:'input',text:prompt()+' '+raw});const parts=tok(raw);let groups=[[]],ops=[];parts.forEach(x=>{if(['|',';','&&'].includes(x)){ops.push(x);groups.push([])}else groups.at(-1).push(x)});let input='';(async()=>{for(let i=0;i<groups.length;i++){const r=await exec(groups[i],input);if(r.out!==undefined){if(ops[i]==='|')input=r.out;else{String(r.out).split('\n').forEach(t=>state.lines.push({type:r.ok===false?'error':'output',text:t}));input=''}}if(r.fs){fs=r.fs;saveFS()}if(r.state)Object.assign(state,r.state);if(ops[i]==='&&'&&!r.ok)break}state.input='';render()})()}
async function exec(a,stdin=''){if(!a.length)return{out:''};a=a.map(expand);let c=a[0],args=a.slice(1);if(state.aliases[c])return exec(tok(state.aliases[c]).concat(args),stdin);const fail=x=>({out:x,ok:false}),ok=x=>({out:x,ok:true});
if(c==='help')return ok('File: ls cd pwd mkdir rmdir touch cat less head tail cp mv rm find grep nano clear history\nShell: bash sh sudo su exit echo export env printenv alias\nSystem: uname hostname uptime free df du lsblk lscpu lspci lsusb ps top htop\nNetwork: ip ifconfig ping traceroute tracepath curl wget dig nslookup host netstat ss route\nPackages: apt apt-get dpkg · Services: systemctl service journalctl\nUsers: whoami id users groups passwd chmod chown · Jobs: kill pkill jobs bg fg\nSpecial: neofetch fastfetch matrix banner motd sysinfo network');
if(c==='pwd')return ok(state.cwd);if(c==='whoami')return ok(state.user);if(c==='hostname')return ok('henry');if(c==='users')return ok('guest user admin root');if(c==='groups')return ok(USERS[state.user].groups.join(' '));if(c==='id')return ok(`uid=${USERS[state.user].uid}(${state.user}) gid=${USERS[state.user].gid}(${state.user}) groups=${USERS[state.user].groups.join(',')}`);
if(c==='cd'){const p=resolve(state.cwd,args[0]??'~'),n=node(p);return n?.type==='dir'?{out:'',state:{cwd:p}}:fail(`bash: cd: ${args[0]??'~'}: No such file or directory`)}
if(c==='ls'){const target=args.find(x=>!x.startsWith('-'))??state.cwd,p=resolve(state.cwd,target),n=node(p);if(!n)return fail(`ls: cannot access '${target}': No such file or directory`);if(n.type==='file')return ok(n.name);let all=args.some(x=>x.includes('a')),long=args.some(x=>x.includes('l'));const xs=Object.values(n.children).filter(x=>all||!x.name.startsWith('.'));return ok(long?xs.map(x=>`${x.mode} 1 ${x.owner.padEnd(6)} ${x.group.padEnd(6)} ${(x.content?.length??0).toString().padStart(5)} Aug 30 17:50 ${x.name}`).join('\n'):xs.map(x=>x.name+(x.type==='dir'?'/':'')).join('  '))}
if(c==='mkdir'||c==='touch'){let n=clone(fs);for(const name of args.filter(x=>!x.startsWith('-'))){const q=parent(resolve(state.cwd,name));if(!q.p?.children)return fail(`${c}: cannot create '${name}'`);if(c==='mkdir')q.p.children[q.name]=dir(q.name,state.user,USERS[state.user].groups[0]);else q.p.children[q.name]=q.p.children[q.name]||file(q.name,'',state.user,USERS[state.user].groups[0])}return{out:'',fs:n}}
if(['cat','less','head','tail'].includes(c)){if(!args[0])return ok(stdin);const n=node(resolve(state.cwd,args[0]));if(!n)return fail(`${c}: ${args[0]}: No such file or directory`);if(n.type==='dir')return fail(`${c}: Is a directory`);let lines=(n.content||'').split('\n');if(c==='head')lines=lines.slice(0,10);if(c==='tail')lines=lines.slice(-10);return ok(lines.join('\n'))}
if(c==='echo')return ok(args.join(' '));if(c==='export'){let env={...state.env};args.forEach(x=>{let i=x.indexOf('=');if(i>0)env[x.slice(0,i)]=x.slice(i+1)});return{out:'',state:{env}}}if(c==='env'||c==='printenv')return ok(Object.entries(state.env).map(([k,v])=>`${k}=${v}`).join('\n'));if(c==='alias'){if(!args.length)return ok(Object.entries(state.aliases).map(([k,v])=>`alias ${k}='${v}'`).join('\n'));let z=args.join(' '),i=z.indexOf('=');return i>0?{out:'',state:{aliases:{...state.aliases,[z.slice(0,i)]:z.slice(i+1)}}}:fail('alias: invalid syntax')}
if(c==='history')return ok(state.history.map((x,i)=>`${String(i+1).padStart(4)}  ${x}`).join('\n'));if(c==='clear')return{out:'',state:{lines:[]}};if(c==='uname')return ok(args.includes('-a')?'Linux henry 6.8.0-virtual #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux':'Linux');if(c==='uptime')return ok(' 17:52:41 up 2:14, 1 user, load average: 0.12, 0.08, 0.03');if(c==='free')return ok('               total        used        free\nMem:        16384000     3481600    11821000\nSwap:        4194304           0     4194304');if(c==='df')return ok('Filesystem      Size  Used Avail Use% Mounted on\nvirtual-disk    128G   13G  115G  10% /');if(c==='du')return ok('12K /etc\n128M /usr\n420M /home/henry\n620M /var');if(c==='lsblk')return ok('NAME   SIZE TYPE MOUNTPOINT\nvda    128G disk\n└─vda1 128G part /');if(c==='lscpu')return ok('Architecture: x86_64\nCPU(s): 8\nModel name: Virtual CPU\nThread(s) per core: 2');if(c==='lspci')return ok('00:02.0 VGA compatible controller: Virtual Graphics Adapter\n00:03.0 Ethernet controller: Virtual Network Device');if(c==='lsusb')return ok('Bus 001 Device 001: Virtual USB root hub');
if(c==='ps')return ok('  PID USER  %CPU %MEM COMMAND\n1 root  0.0 0.1 systemd --system\n621 root 0.0 0.2 NetworkManager\n1042 user 1.3 2.1 bash\n1180 user 0.5 1.0 terminal-ui');if(c==='top'||c==='htop')return ok('Tasks: 24 total, 1 running, 23 sleeping\n%Cpu(s): 2.1 us, 0.9 sy, 97.0 id\nMiB Mem : 16000 total, 3400 used, 11800 free');
if(c==='ip'||c==='ifconfig')return ok('eth0: UP mtu 1500\n    inet 192.168.1.42 netmask 255.255.255.0\nlo: UP LOOPBACK\n    inet 127.0.0.1');if(c==='ping')return ok(`${args[0]||'localhost'} (192.168.1.1)\n64 bytes from ${args[0]||'localhost'}: icmp_seq=1 ttl=57 time=12.4 ms\n64 bytes from ${args[0]||'localhost'}: icmp_seq=2 ttl=57 time=11.8 ms\n2 packets transmitted, 2 received, 0% packet loss\n(simulated: browsers cannot issue raw ICMP)`);if(['traceroute','tracepath'].includes(c))return ok('1  192.168.1.1  1.3 ms\n2  10.0.0.1  5.7 ms\n3  target 12.9 ms\n(simulated route)');if(['dig','nslookup','host'].includes(c))return ok(`Server: 1.1.1.1\nName: ${args[0]||'example.com'}\nAddress: 93.184.216.34\n(simulated DNS response)`);if(['netstat','ss'].includes(c))return ok('tcp LISTEN 0.0.0.0:22 sshd (simulated)\ntcp ESTAB 192.168.1.42:443 browser-fetch');if(c==='route')return ok('default via 192.168.1.1 dev eth0\n192.168.1.0/24 dev eth0');
if(c==='curl'||c==='wget'){const url=args.find(x=>/^https?:\/\//i.test(x));if(!url)return fail(`${c}: URL required`);try{const r=await fetch(url);return ok(`${c}: HTTP ${r.status} ${r.statusText}\ncontent-type: ${r.headers.get('content-type')||'unknown'}\n\n${(await r.text()).slice(0,7000)}`)}catch{return fail(`${c}: blocked by browser CORS/network policy. No backend request was made.`)}}
if(c==='neofetch'||c==='fastfetch')return ok(`user@henry                 Ubuntu Simulator 24.04 LTS\n-----------------         --------------------------\nOS: Ubuntu Simulator x86_64\nHost: Browser Virtual Machine\nKernel: 6.8.0-virtual\nShell: ${state.env.SHELL.split('/').pop()}\nCPU: Virtual CPU (8 cores)\nMemory: 16 GiB\nDisk: 128 GiB\nUptime: 02:14:37\nNetwork: 192.168.1.42`);if(c==='sysinfo')return ok('Hostname: henry\nOS: Ubuntu Simulator 24.04 LTS\nKernel: 6.8.0-virtual\nArchitecture: x86_64\nCPU: 8 vCPU\nRAM: 16 GiB\nStorage: 128 GiB');if(c==='network')return ok('eth0 192.168.1.42/24 · gateway 192.168.1.1 · DNS 1.1.1.1');if(c==='motd')return ok('Welcome to Ubuntu Simulator 24.04 LTS.\nLast login: today on tty1');if(c==='banner')return ok('██╗  ██╗███████╗███╗   ██╗██████╗ ██╗   ██╗\n██║  ██║██╔════╝████╗  ██║██╔══██╗╚██╗ ██╔╝\n███████║█████╗  ██╔██╗ ██║██████╔╝ ╚████╔╝');if(c==='matrix')return ok('1 0 1 1 0 0 1 0 1 1\n0 1 0 0 1 1 0 1 0 1\n1 1 0 1 0 1 1 0 0 1');
if(['apt','apt-get','dpkg','systemctl','service','shutdown','reboot','chmod','chown'].includes(c)){if(state.user!=='root')return fail(`${c}: Permission denied`);return ok(c==='apt'&&args[0]==='update'?'Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease\nHit:2 http://security.ubuntu.com/ubuntu noble-security InRelease\nReading package lists... Done\n1842 packages can be upgraded.':`${c}: simulated operation completed successfully.`)}
if(c==='sudo'||c==='su'){let target=c==='sudo'?'root':(args[0]||'root');if(!USERS[target])return fail(`${c}: unknown user ${target}`);state.password={target};return ok(`[${c}] password for ${target}:`)}if(c==='bash'||c==='sh')return ok(`Entering nested ${c} shell. Type exit to return.`);if(c==='exit')return ok(state.stack.length?'logout':'logout');if(c==='passwd')return ok('New password:\nRetype new password:\npasswd: password updated successfully (simulated).');if(c==='kill'||c==='pkill')return ok('Terminated simulated process.');if(c==='jobs')return ok('[1]+ Running sleep 999 &');if(c==='bg'||c==='fg')return ok(`${c}: simulated job control completed`);if(c==='which')return ok(COMMANDS.includes(args[0])?`/usr/bin/${args[0]}`:'');if(c==='date')return ok(new Date().toString());if(c==='timedatectl')return ok(`Local time: ${new Date().toLocaleString()}\nTime zone: Europe/Paris\nNTP service: active (simulated)`);if(c==='find'){const start=resolve(state.cwd,args[0]||'.'),pattern=args.includes('-name')?args[args.indexOf('-name')+1]:'*',hits=[];function walk(p,n){if(pattern==='*'||n.name===pattern)hits.push(p);if(n.type==='dir')Object.values(n.children).forEach(x=>walk(resolve(p,x.name),x))}const n=node(start);if(n)walk(start,n);return ok(hits.join('\n'))}if(c==='rm'||c==='rmdir'||c==='cp'||c==='mv')return ok(`${c}: simulated filesystem operation completed`);return fail(`bash: ${c}: command not found`)}

async function key(e){if(state.password){if(e.key==='Enter'){const target=state.password.target;if(state.input===USERS[target].password){state.login.push({user:state.user,cwd:state.cwd});state.user=target;state.cwd=USERS[target].home;state.env={...state.env,HOME:USERS[target].home};state.password=null;state.input='';render()}else{state.password=null;state.input='';print('Sorry, try again.','error')}}return}if(e.key==='Enter'){e.preventDefault();runLine(state.input)}else if(e.key==='ArrowUp'){e.preventDefault();if(state.history.length){state.hi=state.hi<0?state.history.length-1:Math.max(0,state.hi-1);state.input=state.history[state.hi];render()}}else if(e.key==='ArrowDown'){e.preventDefault();state.hi++;state.input=state.hi<state.history.length?state.history[state.hi]:'';render()}else if(e.key==='Tab'){e.preventDefault();const x=state.input.split(/\s+/).pop()||'',m=COMMANDS.filter(c=>c.startsWith(x));if(m.length===1&&!state.input.includes(' ')){state.input=state.input.slice(0,-x.length)+m[0]+' ';render()}else if(m.length>1&&!state.input.includes(' '))print(m.join('  '))}else if(e.ctrlKey&&e.key.toLowerCase()==='l'){e.preventDefault();state.lines=[];render()}else if(e.ctrlKey&&e.key.toLowerCase()==='c'){e.preventDefault();state.input='';print('^C','system')}}
function panel(kind){const side=document.getElementById('sidepanel');side.classList.remove('hidden');let body='';if(kind==='files'){const n=node(state.cwd);body=`<div class="panel-head"><div><small class="muted">EXPLORER</small><h2>${state.cwd}</h2></div><button onclick="closePanel()">×</button></div><div class="panel-body panel-list">${Object.values(n?.children||{}).map(x=>`<button>${x.type==='dir'?'▰':'□'} ${x.name}</button>`).join('')}</div>`}else if(kind==='processes')body=`<div class="panel-head"><div><small class="muted">SYSTEM</small><h2>Processes</h2></div><button onclick="closePanel()">×</button></div><div class="panel-body"><div class="card"><strong>24 tasks</strong><small>2.1% CPU · 3.4 GiB RAM</small></div><pre class="card">1 root systemd\n621 root NetworkManager\n1042 user bash\n1180 user terminal-ui</pre></div>`;else if(kind==='system')body=`<div class="panel-head"><div><small class="muted">SYSTEM</small><h2>System info</h2></div><button onclick="closePanel()">×</button></div><div class="panel-body"><div class="card"><strong>Virtual CPU</strong><small>8 cores</small></div><div class="card"><strong>Memory</strong><small>16 GiB</small></div><div class="card"><strong>Storage</strong><small>128 GiB virtual disk</small></div></div>`;else if(kind==='network')body=`<div class="panel-head"><div><small class="muted">NETWORK</small><h2>Network</h2></div><button onclick="closePanel()">×</button></div><div class="panel-body"><div class="card"><strong>eth0</strong><small>192.168.1.42/24 · gateway 192.168.1.1</small></div><div class="card"><strong>HTTP bridge</strong><small>Real CORS-allowed fetch · raw ICMP/TCP simulated</small></div></div>`;side.innerHTML=body}
function closePanel(){document.getElementById('sidepanel').classList.add('hidden')}
function searchModal(){const m=document.getElementById('modal');m.classList.remove('hidden');m.innerHTML=`<div class="search-box"><span>⌕</span><input id="search-input" placeholder="Search terminal output…"><span>${state.lines.length} lines</span><button onclick="document.getElementById('modal').classList.add('hidden')">×</button></div>`;document.getElementById('search-input').focus()}
function fullscreen(){if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='fullscreen')fullscreen();else if(a==='search')searchModal();else panel(a)});document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='f'){e.preventDefault();searchModal()}});
sessions=[newSession()];state=sessions[0];render();
